### ISSUE TITLE
Implementation whisper model in Davinci 18.5 beta 2

### ISSUE THREAD

**Issue by VadimTiupalov** [octimot/StoryToolkitAI#101]
Hello, Octavian!

In 18.5 beta 2 release of davinci resolve I've noticed new feature: 

**• Scripting API support to create subtitles from timeline audio.
• Scripting API support to transcribe source clips.**

Does it mean that now there is an ability to implement any voice to text model inside Davinci resolve and make it in Davinci UI style? And if the answer is yes - will you do it with whisper model and release it in near future? Thanks in advance for answer

Best wishes, 
Vadim

**Comment by octimot** [comment]
Hey Vadim!

I haven't seen the API documentation for 18.5 beta 2, but I would be surprised if you could change the internal model used by Resolve to transcribe. Most likely it's just a "start transcription" command and nothing else.

>  And if the answer is yes - will you do it with whisper model and release it in near future?
Even if that is possible, probably no, because we would be technically doing BMs work for free.

Keep in mind that the Resolve integration is only one of the features of the tool, and that many people use StoryToolkitAI with other software too...

I feel we would really be doing a de-service to the community by focusing on fixing things in BM's backyard... I would prefer that we invest this work into making transcriptions faster/better and integrating other AI coolness instead of that.

Cheers!
