### ISSUE TITLE
Non-standalone install failed at git clone (permission denied)

### ISSUE THREAD

**Issue by Europa2010AD** [octimot/StoryToolkitAI#116]
**Describe the bug**
Was following the non-standalone installation procedure step by step, everything was fine until the command `git clone git@github.com:octimot/StoryToolkitAI.git`. Returned a "Permission denied (publickey)" message.

**To Reproduce**
1. Go to desired folder for installing StoryToolkitAI
2. Open a terminal there.
3. Enter `git clone git@github.com:octimot/StoryToolkitAI.git`
4. Error message appears as follows:
Cloning into 'StoryToolkitAI'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**System (please complete the following information):**
 - OS: MacOS 13.4.1
 - Python versions installed on machine: 3.10
 - StoryToolkitAI Version: the latest non-patreon version

**Comment by octimot** [comment]
Hey there!

You're getting this because you probably don't have your keys set up in your GitHub account, so you can either:

1. Clone the repository using HTTPS instead of SSH:

```
git clone https://github.com/octimot/StoryToolkitAI.git
```

OR

2. Set up SSH for Github by following the guide here: https://docs.github.com/en/authentication/connecting-to-github-with-ssh and then try to clone using the command you tried to use again.

I will add this to the INSTALLATION.md file, thanks for pointing it out!

But, first, please let me know if it works.

Cheers!

**Comment by Europa2010AD** [comment]
>     1. Clone the repository using HTTPS instead of SSH:
> 
> 
> ```
> git clone https://github.com/octimot/StoryToolkitAI.git
> ```
This works perfectly (setting up SSH for Github is kinda over my head at the moment, so I chose the easy route)!

Thanks for your help, @octimot

**Comment by Europa2010AD** [comment]
By the way, on a somewhat related note:

While following the installation instructions, at the end of Step 7 (Install OpenAI Whisper), it was mentioned that users might encounter an error saying Rust is required. I didn't run into this issue, however I did run into this during Step 8 instead (when the `pip install -r StoryToolkitAI/requirements.txt` command is run.
