### ISSUE TITLE
Launch fails with Resolve installed

### ISSUE THREAD

**Issue by asb56** [octimot/StoryToolkitAI#123]
**Describe the bug**
Launch fails without obvious error with DaVinci Resolve installed (as opposed to DaVinci Resolve Studio).

**To Reproduce**
Install DaVinci Resolve. Attempt to launch StoryToolkitAI.

**Expected behavior**
As I understanded it, Resolve's scripting module only ships with the paid version of the software. I assume this is required for the integration to work. In its absence I would expect StoryToolkitAI to launch in standalone mode.

**Log file**
Debug from terminal:
```
DEBUG: 
--------------
Platform: Windows 10
 Platform version: 10.0.22621
 OS: 10 10.0.22621 SP0 Multiprocessor Free  ('', '', '')
 running Python 3.10.11.final.0
--------------
DEBUG: All package requirements met.
DEBUG: Loading config file C:\Users\asbut\StoryToolkitAI\config.json.
INFO: Running StoryToolkitAI version 0.19.1 
DEBUG: Using cuda for Torch.
DEBUG: MotsResolve module initialized.
DEBUG: Trying to load DaVinciResolveScript module...
DEBUG: Found DaVinci Resolve at the default location: C:\Program Files\Blackmagic Design\DaVinci Resolve\
DEBUG: Unable to find module DaVinciResolveScript from PYTHONPATH - trying default locations next

```

**Comment by octimot** [comment]
Hey there!

Unfortunately, there's no way for StoryToolkitAI to know which version of Resolve is installed since the Resolve API or modules don't report this back. 

But, to disable Resolve API altogether from the tool, you can launch it with the argument `--noresolve`:

1. Open up the location where you installed the tool (right click on the desktop shortcut -> Open file location)
2. In the top bar of Windows Explorer, type in `cmd`
3. Then execute `StoryToolkitAI.0.19.1.WIN.exe --noresolve` (or use whatever .exe file you have in that folder)
4. The tool should now launch
5. Then, go to File -> Preferences and Disable Resolve API from the Integrations tab

Alternatively, you could edit your desktop / start bar shortcut to include the --noresolve argument.

Let me know if this helps.

Cheers!
