### ISSUE TITLE
What objects can be searched for?

### ISSUE THREAD

**Issue by mkammes** [octimot/StoryToolkitAI#129]
Is there a list?
OCR?
Logos?

Conversely, what models are being used for this operation that we can dig into their guide on recognizable objects?

Thanks - this looks great!

**Comment by octimot** [comment]
Hey there!

You can pretty much search for literally any object, text etc. and use any sort of vocabulary or grammar that you find fit as long as it's in English.

If you're familiar to how AI image generation works (Midjourney, Stable Diffusion etc.), we like to think that this is basically the reverse of that. It might take a couple of tries to find exactly what you're looking for when it comes to edge stuff, but most of the times the model returns what you're looking for.

We're using the RN50x4 CLIP model since it seems to provide the most balanced results and it's pretty robust when it comes to understanding things. For more info regarding CLIP, check out [this post](https://openai.com/research/clip).

By the way, once the model is downloaded in your local cache, you no longer need an internet connection to search for stuff in your footage as the entire indexing and search process is done locally.

But, just try it and see what I mean...

Cheers!

**Comment by octimot** [comment]
I'm closing this for lack of response but feel free to re-open if you have other questions on the topic.

Cheers

**Comment by mkammes** [comment]
Didn't think I needed to respond!

Thanks for the backend info. Do you anticipate support for other zero-shot models?

Thanks for all of the hard work!
