### ISSUE TITLE
StoryToolkit complains ffmpeg not installed, but it is

### ISSUE THREAD

**Issue by rdacode** [octimot/StoryToolkitAI#15]
Using StoryToolkitAI v0.17.0 on an Intel Mac, OSX 11.4. I installed Homebrew and ffmpeg (if I try to install again terminal says "ffmpeg 5.1.2 is already installed and up-to-date."), but when I launch the app, it alerts me that ffmpeg is not present. ffmpeg is at 
/usr/local/Cellar/ffmpeg/5.1.2. Is this as expected?

**Comment by octimot** [comment]
Thanks for reporting!

The check seems to misfire sometimes on some machines. I'll change the way it's probing for ffmpeg in a future update.

If the tool is transcribing, everything should be fine. If not, please let me know as it might be MacOS sandboxing the standalone app or something similar, and that needs a different approach.

**Comment by rdacode** [comment]
It wouldn't transcribe. My Python installs were a big mess, so I cleaned them up and reinstalled ffmpeg. It still gives the error, but it transcribes now.

**Comment by octimot** [comment]
There was a problem with the freezing process in the standalone app which prevents the app for looking for ffmpeg in the environment variables.

I'll push an update and a new release asap.

Thanks again for the feedback!

**Comment by octimot** [comment]
Alright, this new release should have the ffmpeg check fixed: https://github.com/octimot/StoryToolkitAI/releases/tag/v0.17.1

Let me know if it doesn't work for you.

**Comment by rdacode** [comment]
Confirmed fixed. Thanks!  BTW, in the interim - while the standalone wasn't transcribing - I went through the whole source file install, so I am able to run via Terminal as well. Is there any benefit to doing that instead of using the standalone? Thanks again for building this!

**Comment by octimot** [comment]
> Is there any benefit to doing that instead of using the standalone? Thanks again for building this!

The non-standalone version is being updated more frequently, because it takes a significant amount of time and effort to freeze and test the standalone releases for all platforms. For eg. the non-standalone version is now at v0.17.2 while the latest release is at v0.17.1. [Here](https://github.com/octimot/StoryToolkitAI/commits/main) you see all the commits on the non-standalone code.

BTW, if you want to get the latest updates on the non-standalone version, you simply do a `git pull` in the folder where you installed it.

On the other hand, it's probably much easier to simply click and start the standalone version on your machine, instead of going through the 2-3 command lines.

Also, the standalone version should contain the right Python version and all the packages that it needs to run well (besides ffmpeg).

Besides that, there's not really an advantage having one or the other, unless you want to code, extend etc....
