### ISSUE TITLE
SRT is not available anymore

### ISSUE THREAD

**Issue by salomaoparkour** [octimot/StoryToolkitAI#163]
**Describe the bug**
Whenever I transcribe a video there's no .SRT file output anymore.
Updated from 0.19.5 to 0.24.0 and then the .SRT was gone. Only JSON file is created.

**System**
 - OS: Windows 10
 - Python versions installed on machine: 3.10
 - StoryToolkitAI Version: 0.24.0

**Comment by nkrns** [comment]
# @salomaoparkour @octimot 
bump - Were you able to resolve this issue and if so how?, the issue is marked as closed and I am facing the same issue

**Comment by octimot** [comment]
Starting with version [0.24.0 ](https://github.com/octimot/StoryToolkitAI/blob/main/CHANGELOG.md#changes) the tool no longer automatically exports SRT since most users were complaining that it's creating too many files around transcriptions, so this is in fact intended and not a bug.

We're going to add the option to choose whether to automatically export SRTs after ingest but they will not be updated with when transcriptions are updated as before.

**Comment by nkrns** [comment]
I didn't realize it was an intended change, it was definitely helpful to have .srt exports as a default as media players like VLCs doesn't work with json files as subtitles files. Is there anyway to make .srt as a default option instead of .json transcripts?, as at the moment I would have to manually export all .json files to .srt files individually which can be time consuming from multiple video/audio transcribes

**Comment by octimot** [comment]
The transcription.json file contains much more information than just the transcription - stuff like paths to source audio, transcription titles, index locations etc. In other words, the transcription window will not work without the transcription.json file.

**Comment by helmutgranda** [comment]
In my case the only thing that I am currently using the tool for is to transcribe videos so having the option to automatically being generated is great!

Is this work in progress? I would be curios to see if I can see older source files and see if I could help implement this.

**Comment by octimot** [comment]
@helmutgranda I'm currently working on an update and hopefully will have it up soon! 

The older SRT saving pipeline is a bit outdated for how the tool handles these kinds of files now, so that's why I had to clean up and now refactor. I also wanted to give users the possibility to auto-save files based on other [custom export templates](https://github.com/octimot/StoryToolkitAI/blob/main/FEATURES.md#exporting-using-custom-transcription-export-templates) too, and this will be part of the same pipeline.

I think i'm too far in the process to pass it over, but thanks for trying to help! 

Cheers
