### ISSUE TITLE
StoryToolkitAI is not opening anymore (worked fine before I made a change)

### ISSUE THREAD

**Issue by adishor86** [octimot/StoryToolkitAI#167]
Hi, 

First, Thanks for StoryToolkitAI, it has proven very useful for me. 

Unfortunately I have encountered an issue and Ii can't open the program anymore. 

I fiddled with the preferences and made these 2 changes:

1. I unchecked Disable Resolve Integration (think from memory this was called) it was turned on by default
2. I changed the assistant to the newest version of GPT (the beta one)

I restarted the app when prompted and could not open it anymore. Tried reinstalling multiple times including changing the install location disabling antivirus etc.

It worked just fine for months so I think the issue is related to these two steps. 

II ran the program in CMD as you suggested in another bug report and got this:

The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Exception in thread Thread-4 (check_api_key):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "storytoolkitai\core\storytoolkitai.py", line 620, in check_api_key
AttributeError: 'Logger' object has no attribute 'dbug'. Did you mean: 'debug'?
INFO: Running StoryToolkitAI version 0.23.2 (standalone)
Traceback (most recent call last):
  File "storytoolkitai\integrations\mots_resolve.py", line 166, in get_resolve
ModuleNotFoundError: No module named 'DaVinciResolveScript'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules\DaVinciResolveScript.py", line 25, in <module>
    import fusionscript as script_module
ModuleNotFoundError: No module named 'fusionscript'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "storytoolkitai\__main__.py", line 185, in <module>
  File "storytoolkitai\__main__.py", line 169, in main
  File "storytoolkitai\core\toolkit_ops\toolkit_ops.py", line 201, in __init__
  File "storytoolkitai\core\toolkit_ops\toolkit_ops.py", line 3025, in resolve_enable
  File "storytoolkitai\integrations\mots_resolve.py", line 68, in __init__
  File "storytoolkitai\integrations\mots_resolve.py", line 243, in get_resolve
  File "imp.py", line 172, in load_source
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules\DaVinciResolveScript.py", line 46, in <module>
    script_module = load_dynamic("fusionscript", path + "fusionscript" + ext)
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules\DaVinciResolveScript.py", line 15, in load_dynamic
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
SystemError: initialization of fusionscript failed without raising an exception
[3256] Failed to execute script '__main__' due to unhandled exception!

I am using StoryToolkitAI V.0.23.2

Thank you

**Comment by octimot** [comment]
Hey there!

Let me take each error at a time (there are two in your report actually)

> File "storytoolkitai\core\storytoolkitai.py", line 620, in check_api_key

This was fixed a few updates back with commit (https://github.com/octimot/StoryToolkitAI/commit/71374a67705af736889e5207c5ea5eb90f790ffc) Are you using the standalone or the git version?

Regarding the Resolve issue:

> I unchecked Disable Resolve Integration (think from memory this was called) it was turned on by default

Which basically produces this:
> ModuleNotFoundError: No module named 'DaVinciResolveScript'

Just to make sure I understand - are you trying to disable the Resolve integration or enable it?

Cheers!

**Comment by adishor86** [comment]
Thank you

I am using standalone now.

Actually, I thought of uninstalling Resolve and now the app works just fine.

Now gonna try to reinstall Resolve and see if the problem shows up again. 

What I was trying to do was to figure out how to integrate Story Tool kit with Resolve. Until now I have been making exports of my timelines then using the standalone app to generate transcripts and srts that I would then import back into resolve. 

I was wondering if it were possible with integration to do transcriptions directly into Resolve because I`m transcribing a language that is not supported by default there. 

Would I be able to do this if I managed to integrate with resolve? to do the transcripts directly there without going through the process described above?

Thank you for the fast response

**Comment by octimot** [comment]
Got it!

> What I was trying to do was to figure out how to integrate Story Tool kit with Resolve. Until now I have been making exports of my timelines then using the standalone app to generate transcripts and srts that I would then import back into resolve.
I was wondering if it were possible with integration to do transcriptions directly into Resolve because I`m transcribing a language that is not supported by default there.
Would I be able to do this if I managed to integrate with resolve? to do the transcripts directly there without going through the process described above?

Technically the Resolve integration gives you the option to render out the current timeline and directly ingest it into StoryToolkitAI from the tool itself. So, the advantage to this is that you don't have to manually render out audio/video from resolve and then ingest them. In other words, it automates a few steps from the process and makes things easier, but the result is still the same: you'll still have a rendered out media file and once the transcription is finished, you'll still have to re-import the SRT into Resolve due to the limitations of Resolve API works. See [this](https://github.com/octimot/StoryToolkitAI/blob/main/FEATURES.md#quick-how-to-transcribe) for a quick transcription how to.

But, again, things are easier with the integration turned on, plus you'll have the advantage of not having to enter timecode data if you need it, you can navigate the Resolve timeline directly by clicking on the transcript line in the tool, you can sync markers and then search for them using the semantic search, etc.

> Disable Resolve API - it was marked as turned on before I got myself into this jam and I had turned it off and that is when I could not open the app anymore.

If this setting is checked (active), StoryToolkitAI will not attempt to connect to Resolve at all. But once it's unchecked, it will always try to connect a few times when you start the tool until it fails. Unfortunately, version 0.23.2 had a small typo that makes the app crash after the first unsuccessful attempt - this was fixed in the git version as I mentioned earlier, and we'll be included in the new standalone version too very soon!

The two main things you need to make sure of:
1. You need to have Resolve Studio - the free version of Resolve does not support API connections
2. You need to have Python 3.10 installed from the official Python website (not from windows store or anything else)
[Read this for more details regarding Resolve API](https://github.com/octimot/StoryToolkitAI/blob/main/FEATURES.md#davinci-resolve-studio-integrations).

Hope this helps!
Cheers!

**Comment by adishor86** [comment]
yes, it does help a lot and you have made it very clear. Thank you

Congrats again for the tool and good luck with everything you do

**Comment by octimot** [comment]
Cheers! Thanks!
