### ISSUE TITLE
Include video files in new projects feature

### ISSUE THREAD

**Issue by GypsyAcidQueen** [octimot/StoryToolkitAI#175]
It would be amazing if we could include video index files in the new projects feature, as searching through a single clip doesn't really help us in our B roll search. Imagine if we had several hundred videos indexed for a project, and could search through them all at once to find the exact frame we were looking for. Would be incredible useful!

**Comment by galavera** [comment]
isn't that already possible? Just create a project and add as many video indexes as you want and search through them all simultaneously.

**Comment by GypsyAcidQueen** [comment]
Oh interesting does this already work? I need to test it but I haven't been let in to the private github repo yet.

**Comment by galavera** [comment]
> Oh interesting does this already work? I need to test it but I haven't been let in to the private github repo yet.

how do you get into the private repo?

**Comment by GypsyAcidQueen** [comment]
Become a frequent user on patreon!

**Comment by octimot** [comment]
@GypsyAcidQueen as @galavera pointed out, you can already do this by basically ingesting all the single video clips. Once they're ingested, you should see them all (individually) in the project list and clicking on the "Search" button should go through all of them.

However, we recommend assembling multiple smaller clips into dailies or longer reels to optimize disk reads and RAM. But if this doesn't work for your workflow and you're dealing with hundreds or thousands of clips, you're in uncharted territories, so please let us know how it works! :-D

> Oh interesting does this already work? I need to test it but I haven't been let in to the private github repo yet.

If you're using the git version of the tool, there's no more distinction between public and early private releases since the private repo is no longer active. This was a huge hassle on our side in terms of releases and version management, so we decided to drop it... The early release perk only applies to the standalone version of the tool. I hope this makes sense!

Cheers!
