### ISSUE TITLE
SRT files not exporting after transciption in v0.24.3

### ISSUE THREAD

**Issue by ConnorBarnes88** [octimot/StoryToolkitAI#201]
I created a new repo folder to test the newer versions (Currently version 0.24.3 but I had similar problems with other versions) from a fresh install. The newer versions since 0.23.1 only export JSON files when the transcription is complete. Is there a way to make it export SRT files again like version 0.23.1 does?

I have been running version 0.23.1 mainly because I need the SRT files for editing.  However, I have been looking to update to a newer version because running 0.23.1 has a version conflict every time I spin it up and automatically reinstalls all the packages again. It is a tad tedious but it exports the files I need.

**System**
 - OS: Windows 11
 - Python versions 3.10.11
 - StoryToolkitAI Version 0.24.3

**Comment by octimot** [comment]
This was intentional since a lot of users were complaining about too much bloat files.

But, I've just pushed version 0.24.4 which allows you to specify auto-export formats for transcriptions during ingest and while editing (https://github.com/octimot/StoryToolkitAI/commit/13f66ac3bb95381007f4001582162a82eab3f974)

Simply add `srt` in Preferences -> Ingest -> "Auto-Save Additional Formats" field and the tool should automatically export the SRT's for you.

Cheers!
