### ISSUE TITLE
Presets or Default for Settings

### ISSUE THREAD

**Issue by Paddywack0** [octimot/StoryToolkitAI#21]
Would it be possible to have presets or a default setting for the Transcription Settings. Pretty much all of my transcriptions are going to be native English using CUDA etc. It would be nice to have that set as my default.

**Comment by octimot** [comment]
Currently, you can manually set the `whisper_model_name` and `whisper_device` in the config.json file located either in`/Users/[YOUR USER]/StoryToolkitAI` (MacOS) or `C:\Users\[YOUR USER]\StoryToolkitAI` (Windows). 

Just make sure that you keep the same syntax as you found it or you'll need to delete the file to get back to default.

`transcription_default_language` setting will be added in the next update.

Keep in mind that if you have the device set to Auto and CUDA is available on your machine, the tool will auto select that instead of the CPU (so no need for an additional default setting).

**Comment by Paddywack0** [comment]
Thanks. Will take a look

**Comment by octimot** [comment]
@Paddywack0 Just released version 0.17.16 standalone which incorporates the `Skip Transcription Settings` feature added a while back git version.

In other words, if you check `Skip Transcription Settings` in your Preferences window, the tool will automatically start to transcribe based on the default transcription preferences you've set up without asking you to fill them up each time.

Cheers!

**Comment by Paddywack0** [comment]
Brilliant. Thanks
