### ISSUE TITLE
Standalone app does not open on Windows (possible issues with Resolve API or Python)

### ISSUE THREAD

**Issue by yokhalel** [octimot/StoryToolkitAI#25]
Hey guys,

The app won't open up for me. I launched storytoolkitai (standalone) but the command line keeps disappearing after these messages in the pic. No difference if i launch it with admin privilege

![grafik](https://user-images.githubusercontent.com/118747939/203080634-cb267740-29f0-4ec9-815c-8a1b871bde1f.png)

**Comment by octimot** [comment]
Hey there,

This is highly likely due to a problem with one of the following:
1. The Resolve API is unresponsive for some reason
2. You might have multiple Python installations on your machine which are colliding with each other and creating chaos

Could you please post the last few lines starting with `Platform:` from the app log stored in `C:\Users\[YOUR USER]\StoryToolkitAI\app.log`? Or simply attach the whole app.log file to this thread.

That might give us more clues to what is happening.

**Comment by yokhalel** [comment]
[app.log](https://github.com/octimot/StoryToolkitAI/files/10058622/app.log)
I think you might be onto something, there you go mate!

**Comment by octimot** [comment]
Yea, it seems to be some chaos happening in your environment.

First, the silly question: Are you trying to run it with Resolve Studio 18?

If yes, do you have any sort of Python installed on your machine? 

If you do, and you don't need it, simply uninstall it (all of them), and then give it another try.

Let me know if this works.

**Comment by yokhalel** [comment]
Yes I'm on Resolve Studio 18.1Build 16

i uninstalled python and rebooted, still the same :/ 
[app.log](https://github.com/octimot/StoryToolkitAI/files/10059497/app.log)

**Comment by octimot** [comment]
Just to be sure, what happens when you run the following commands in a command prompt?

```
python --version
```
or
```
python3 --version
```
or
```
py --version
```

**Comment by yokhalel** [comment]
![grafik](https://user-images.githubusercontent.com/118747939/203131559-3d9386bd-4d96-4919-bfd0-93f9f65eb4e2.png)
It says "Python could not be found. Run the link with no arguments to install it from the Microsoft Store, or disable this link at.."

**Comment by octimot** [comment]
Schei**e. 

Alright! 

It might be that you still have some remnants laying around that are doing weirdness to the Resolve install. So I recommend re-installing Python 3.9 which should reset all that stuff: https://www.python.org/downloads/release/python-3912/ - see [Windows installer (64-bit)](https://www.python.org/ftp/python/3.9.12/python-3.9.12-amd64.exe)

Fingers crossed that this works.

**Comment by yokhalel** [comment]
Alter GEIL!

**Comment by yzorro** [comment]
Just adding some feedback (Win 11 3080 CUDA, DR 18.1.1. Build 7)
Am no programmer type. Very glad to have StoryToolkitAI standalone option. 
Standalone version didn't work from the get-go.
I then added the transcription_WAV custom preset, still didn't work.
I then installed python 3912, also make sure to use PCM test file, seemed to work, but when fetching 'large' database, it "failed", after multiple tries.
I installed ffmpeg (Release ver 5.1.2 essential build), it now works. Transcribe, transcribe + translate work, all produce good result.

I use a Korean talk show with dialog and laughing audience noise for test. Purposely use H265/HEVC.

The same video tested with mono vs stereo, mono produces result, stereo has gibberish.

What still doesn't work as expected = translate on its own. No matter which Source Language I picked, it always spits out English. Probably an issue on the Whisper side.

(by the way)
Whisper transcribing from Korean to English is more accurate than from Korean to Chinese.
Database size matters: There is significant qualitative accuracy/ artfulness between medium vs large when transcribing (from Korean) into English/ Chinese.

Suggestion: would be nice to have a 'Keep on top' for the 7 button transcribe stage panel.

Thank you octimot for this elegant solution. Looking forward to further development.

**Comment by Nargot1** [comment]
I have redownloaded python and ffmpeg. and still doesnt work

**Comment by octimot** [comment]
> I have redownloaded python and ffmpeg. and still doesnt work

Did you also uninstall all other python installations on your machine?

**Comment by medoro** [comment]
Unable to find module DaVinciResolveScript from PYTHONPATH - trying default locations next (mots_resolve.py:154) on log file.... I tried the steps listed here...

**Comment by vibes24** [comment]
As a person with a hearing loss, I am really interested in this tool. I have Resolve 18. I have installed the stand alone tool however it would not run. I want to clarify after reading some various instructions and discussions. It's little confusing.

You said python isn't required but "due to conflicting installation" we should install python 3.9.x (There is no python on my system as far I could tell. Do you mean that Davinci Resolve installed python that isn't visible to the system? (Windows 10).

I see some respondents saying they tried installing python and ffmpeg without luck. I do not want to be installing unnecessary program files unless it's absolutely required. Am I required to install ffmpeg along with standalone tool?

What's the next steps for me? I see no error messages on the command prompt that disappears quickly after opening.
Thanks.

**Comment by octimot** [comment]
Hey there!

> I have Resolve 18. I have installed the stand alone tool however it would not run.

Do you have Resolve 18 Studio? Which standalone version of the tool are you trying to install?


> You said python isn't required but "due to conflicting installation" we should install python 3.9.x (There is no python on my system as far I could tell. 

I'm trying to figure out where was the "conflicting installation" mentioned, could you please point me to the respective page?


> Do you mean that Davinci Resolve installed python that isn't visible to the system? (Windows 10).

No. Python doesn't usually come with Resolve, but some users do have multiple versions of Resolve on their machines for different reasons. If that is the case, any Python > 3.9 installed on the system will prevent the tool from connecting to Resolve because Resolve seems to choose the latest version available on the system.

Based on your log files, there doesn't seem to be any conflicting python versions on your system, but maybe you had it installed in the past (or something installed it) and that left some weird artefacts. I would recommend installing Python 3.9 from the [official source ](https://www.python.org/ftp/python/3.9.13/python-3.9.13-amd64.exe) which usually cleans up all weirdness.


> I do not want to be installing unnecessary program files unless it's absolutely required. Am I required to install ffmpeg along with standalone tool?

Short answer, no, you don't need to install ffmpeg, but you do need to make sure you're feeding the tool the right format files for the best possible results. Please see the installation instructions on the release page mentioning the format etc. and let me know if they're not clear enough and where.

> Checked the log file and apparently it could not find the DaVinciResolveScript. How do I add it?
```
2023-04-10 20:31:56,044 - StAI - DEBUG: Unable to find module DaVinciResolveScript from PYTHONPATH - trying default locations next (mots_resolve.py:236)
```
Your assessment is incomplete - it is unable to find "DaVinciResolveScript from PYTHONPATH" and it's proceeding to find it in the default locations, which it probably does but then crashes.

Let me know if this helps.

Cheers!

**Comment by vibes24** [comment]
Thanks for quick response.
Sorry. I do have Resolve Studio 18.1.4

Sorry. I mean conflicting "statements" regarding installation - "you don't need python but you have to install python". Even on platforms that does not have python installed, python should be installed to "resolve conflicting python versions". Even your Patreon page states that those who subscribe will get the "standalone app without requiring python installation" (https://www.patreon.com/StoryToolkitAI).

Statements like these being posted on your pages/support pages (issue 25), etc is really confusing me. Basically, I think the general statement states that you do need to install python.

I assessed that the tool did not find "DavinciRsolveScript" because it did not state that it found anything in the default location like it did for another "missing" script:
2023-04-10 20:31:56,043 - StAI - DEBUG: Trying to load DaVinciResolveScript module... (mots_resolve.py:159)
2023-04-10 20:31:56,044 - StAI - DEBUG: **Found** DaVinci Resolve at the default location: C:\Program Files\Blackmagic Design\DaVinci Resolve\ (mots_resolve.py:224)

The log did not state that it found anything before shutting down. That was my assessment. I understand that you are busy to care about the language. You care about coding and you know more about this than me. 
I've went ahead and installed python 3.9.13

While the tool now loads. I have multiple errors which transcription fails every time. I will make a new post about.

**Comment by octimot** [comment]
@vibes24 

>I understand that you are busy to care about the language and you know more than me. I am just trying to make sense of the situation however, I've went ahead and installed python 3.9.13

I'm glad you solved it! Sorry for being so short and direct. I hope you understand that it's difficult to repeat in detail the same solution over and over again - this takes a lot of time and resources from our side. The solution to install Python 3.9.13 is only a few posts higher above your initial report (https://github.com/octimot/StoryToolkitAI/issues/25#issuecomment-1322514367). 

> Basically, I think the general statement states that you do need to install python.

No, this is not what the documentation is stating because it would be incorrect.

>  I mean conflicting "statements" regarding installation - "you don't need python but you have to install python". 

> Even your Patreon page states that those who subscribe will get the "standalone app without requiring python installation"

The standalone version does work without the need for a Python installation for the great majority of users.
The only case where the standalone app does require the user to install Python applies to a very small percentage of users who are part of a sub-group of users that use the tool with Resolve, because Resolve is actually causing this indirectly.
So, no... Python is not needed for the standalone version to work, except for that very specific case - see **Notes for Windows** in the [standalone release page](https://github.com/octimot/StoryToolkitAI/releases/tag/v0.17.16).

Please don't get me wrong, your feedback is important and much appreciated, but simply don't see any differences between the documentation and the actual installation process. But, again, if you have a direct proposal for different wording that would make things clearer, I'd be happy to follow up.

Cheers!
