### ISSUE TITLE
Descript workflow - word for word editing feature request

### ISSUE THREAD

**Issue by rexelbartolome** [octimot/StoryToolkitAI#36]
So just read this really cool word-level timed transcription https://github.com/openai/whisper/discussions/684 and I though maybe that could be implemented so that when editing, you can click a word in the Transcription Log then it jumps to that specific word.

Mainly thinking about this workflow so that it's more similar to Descript where you edit the timeline through phrases and words instead of scrubbing through the actual timeline. Right now, the issue is of course when you make an edit in the resolve timeline, that section doesn't get updated in the log. Then the log gets desynced because the timings are now different compared to the timeline. So I thought maybe we could delete the words in the log then sync the deleted words' timecodes to the resolve timeline. 

Currently, I just set it up where I only use the log for navigation and when I cut down stuff from the timeline, I retain the gaps so the log stays in sync.

The advanced search is really cool for this one too: you can type in "repeating phrases" then it would spit out the times the speakers repeat and rephrase themselves, so you can clearly see which parts need some editing. Unfortunate that it only shows up the top 10 results, so maybe another feature to have a "Load more" button or maybe it reactively loads more results once you scroll down more.

**Comment by octimot** [comment]
> Mainly thinking about this workflow so that it's more similar to Descript where you edit the timeline through phrases and words instead of scrubbing through the actual timeline. Right now, the issue is of course when you make an edit in the resolve timeline, that section doesn't get updated in the log. Then the log gets desynced because the timings are now different compared to the timeline. So I thought maybe we could delete the words in the log then sync the deleted words' timecodes to the resolve timeline.

This would be very difficult to implement given all the constraints we have on the Resolve API side...

We use a 3 or 4 -point editing workflow, which implies that the transcribed timelines (dailies) are left untouched in terms of timecode and pull the transcribed footage into selects or rough cut timelines to actually edit the final picture. If you're interested in this workflow, let me know and I can detail it and send you some references!

Since I don't really see how this could be implemented unless we invest a significant amount of development time - again, this is very very difficult to implement since it involves constantly pinging Resolve for timeline changes which is not really feasible and would make everything very slow, I'll close the issue. But feel free to comment further and keep the discussion open, and maybe we find a solution to make it happen in the future!

Regarding word-level times, that will definitely be implemented in the very near future (i.e. early 2023), but we just have to attend to some more urgent updates before that! 

> The advanced search is really cool for this one too: you can type in "repeating phrases" then it would spit out the times the speakers repeat and rephrase themselves, so you can clearly see which parts need some editing. Unfortunate that it only shows up the top 10 results, so maybe another feature to have a "Load more" button or maybe it reactively loads more results once you scroll down more.

You can enter the number of top results the tool gives you when searching, read this - see `[max_results]`:
https://github.com/octimot/StoryToolkitAI#advanced-transcript-search

**Comment by rexelbartolome** [comment]
ahhh i understand. It's the first time I've heard 3/4 point editing. After some reading, is it basically like this? 
![image](https://user-images.githubusercontent.com/88552647/210048012-dfd561c4-0197-408f-865f-10de21c6bebb.png)
Would love to know more about it so please elaborate :)
