### ISSUE TITLE
force to open with english lang?

### ISSUE THREAD

**Issue by ushere2** [octimot/StoryToolkitAI#38]
hi. and using with resolve (with fantastic results in general), however, i have two interview subjects where story... chooses 'hebrew' as the lang. for some reason, (the interviewees are Israeli, but speaking english. is there a way to force story to always open in english?

thanks

well, just tried in stand-alone mode, and it's still choosing 'hebrew' as the default language.  since i don't do any multilingual work, where can i set default to english?

many thanks and a very merry whatever ;-)

**Comment by ushere2** [comment]
hi Octavian,

First, thanks for the most amazing piece of software I've ever used, well,
forever.

I finally figured out where to change language in the config... and now
working perfectly on the two Israelis.

though they were both speaking in English, was story... using their accents
to judge language?

again, amazing integration and ai

take care, stay well

leslie

**Comment by octimot** [comment]
> though they were both speaking in English, was story... using their accents
to judge language?

This is an interesting find from your part!

I guess the Whisper model is biased to think that Hebrew sounding English is Hebrew, instead of English. Maybe OpenAI used videos which were combining Hebrew and English words in the same sentence to train the model and therefore the bias was created, but it's hard to judge from this side...

Cheers!
