### ISSUE TITLE
error on opening 17.5WIN

### ISSUE THREAD

**Issue by camills** [octimot/StoryToolkitAI#48]
I get this window flashing up on the screen when trying to open the .exe file. Any ideas? Am I missing some kind of Python library?
![TapScanner 01-20-2023-11꞉31_20230120_113226_309_17 (1)](https://user-images.githubusercontent.com/41301254/213687188-a667c007-f53d-485d-a6ae-9c429b4cbe8c.jpg)

**Comment by octimot** [comment]
This shouldn't happen for the standalone version as it has all the modules that it needs frozen and packed within itself.

Do you have other python installations on your system? They might interfere with the standalone tool.

Sorry for the late reply!  Cheers!

**Comment by camills** [comment]
I've tried installing and deleting several different versions of Python as
suggested by other users - alas to no effect. I also run multiple screens
(also another user comment), but cannot see how that would affect things.
Looking at the log on the CLI I attached, it seems to be looking for a
specific file - tho' that file does seem to be present. I copied it to a
couple of other directories, but without any effect. Worth noting btw that
if I just open the exe file, I get the CLI which just hangs forever. Only
by using 'open as system admin' do I get the error message. Does that
suggest anything?

It's such a shame 'cos this is an absolutely brilliant idea; I just cannot
get it past first base. Thanks for any help you can provide.....

**Comment by octimot** [comment]
> Worth noting btw that if I just open the exe file, I get the CLI which just hangs forever. Only by using 'open as system admin' do I get the error message. Does that suggest anything?

Yes, this is weird, but kind of expected since you're no longer using the "owner" of the python environment, but the system admin. Therefore, the errors you get în this case are not relevant for what is happening when you open the tool using the other user.

> Worth noting btw that if I just open the exe file, I get the CLI which just hangs forever.

Most likely, this happens due to an issue with the Resolve API. The tool sees that Resolve exists and tries to access the API, but the API hangs for an unknown reason and without triggering any error or exception...

This is very specific to python conflicts on one's system. 

If you followed the documentation carefully - Resolve settings, having Resolve in its default folder etc. - my recommendation is to remove ALL python installs from your system temporarily and see if the tool starts, while having them all removed. Also, you can try to reinstall only Python 3.9 from the official python website (not via Microsoft Store!), since this has the tendency to clean up weird environment variables that Resolve might pick up - see other open and closed issues in this github for more details on that.

Again, the standalone version should have everything that it needs packed and frozen within its files, but it needs a clean system and environment to communicate with Resolve.

Hope this helps!

**Comment by camills** [comment]
Thanks. I've tried this already, but now I think I have to deinstall, clean
and reinstall everything to see if that works.
