### ISSUE TITLE
ModuleNotFoundError: No module named ...

### ISSUE THREAD

**Issue by theschlaepfer** [octimot/StoryToolkitAI#5]
Encountering this issue after installing everything and running `python StoryToolkitAI/app.py
`

`Traceback (most recent call last):
  File "/Users/officeeditor1/Movies/StoryToolKitAI/StoryToolkitAI/app.py", line 14, in <module>
    import mots_resolve
  File "/Users/officeeditor1/Movies/StoryToolKitAI/StoryToolkitAI/mots_resolve.py", line 15, in <module>
    from timecode import Timecode
ModuleNotFoundError: No module named 'timecode'`

Any suggestions?

**Comment by octimot** [comment]
Hey! Did you follow all the installation steps, including 
`pip install -r StoryToolkitAI/requirements.txt` ?

Cheers

**Comment by theschlaepfer** [comment]
Yup. Not running it in a virtual environment so maybe that's the issue. This is what I see regarding timecode when I run the command you suggested:

`Requirement already satisfied: timecode==1.3.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r StoryToolkitAI/requirements.txt (line 15)) (1.3.1)
`

**Comment by octimot** [comment]
This is weird. 
You could try to uninstall timecode then install it back.
I would suggest to set up a virtual environment and install the requirements from scratch - maybe there is something else installed in your python package that is colliding.

**Comment by CVeyVey** [comment]
I had the same problem. My system had python 3.9 and 3.10 installed.
Wild guess: maybe the script looks for the module timecode in 3.9 while requirements looks in 3.10?
Uninstalling both, only installing 3.9, pulling the git via commandline and running it in a virtual environment as described in the readme solved it. Make sure you run
`init git`on the folder you want to have the script in before pulling.

**Comment by octimot** [comment]
Yes multiple Python versions on the same OS are sometimes problematic.

I think simply using a virtual environment and following  the installation instructions should work.

I wouldn't recommend uninstalling Python 3.10 since I believe it may mess up some system utilities on Mac OS.

Also, git init isn't necessary when you git clone, since it's basically done automatically.

Cheers!

**Comment by cmactavish** [comment]
I've just run into this issue trying the installation as per instructions, with the virtual environment. I did had to use `sudo -H pip3 install virtualenv` however when installing that part, as it wasn't working otherwise.

**Comment by octimot** [comment]
Hey there!

There's a lot of info to unpack so let me take it one by one. :))

## 1. Installation errors
This might be obvious, but mxqake sure you are reading the console when you're installing stuff to track any conflicts or errors. If something is skipped or if it failed, any installation step that follows might not work as expected.

## 2. Installing packages inside the virtual environment
First, it's very important that all the `pip` or `pip3` commands you issue after step 5, you issue them inside the virtual environment.

Important to know:
`pip install virtualenv` - installs the package virtualenv on your machine
`virtualenv -p python3.9 venv` - creates a virtual environment which will almost completely "isolate" the tool from the rest of the stuff on your machine

In principle, the only things that are not "isolated" are your Python@3.9, Tcl/Tk, Python-tk@3.9, git and ffmpeg installations which have to be first installed outside of the virtual environment so that the virtual environment can link to them when starting the tool.


## 3. pip vs pip3
Unless you have Python 2 installed on your machine, there is no reason to use `pip3` instead of `pip`

To make sure that `pip` is using the right Python version, simply run `pip --version` and it should display the Python version it's using. If that is python 3.9, that is what you need and it will work fine for the installation tool.

If you see another version of Python 3 there (like 3.5, 3.10 etc.), it means that you are outside the Python 3.9 virtual environment (redo installation steps 2 to 4 to make sure everything is installed correctly) 

If you see something like Python 2.7, simply do `pip3 --version` to make sure (again) that it's using Python 3.9, and if not, repeat steps 2-4 but with `pip3` where necessary.

BTW, if you don't have pip installed, any modern version of Mac OS should be able to do `python3.9 -m ensurepip` to install it.


## 4. The package error

Starting with version 0.16.15, the tool first checks if all the packages that it needs are installed correctly in your environment. An important thing to note is that the `requirements.txt` file is very specific about which version of which package it needs.
That is why you absolutely need to do `pip install -r requirements.txt` inside the virtual environment and **absolutely not install individual packages manually** like you showed in your message.

Sorry to repeat, but to make it clear, absolutely do not do `pip3 install timecode` or anything else outside of `requirements.txt`. Whisper and some of the packages that are required are very picky about specific package versions!

So, this warning that you received:

```
WARNING: Some of the packages required to run StoryToolkitAI are missing from your Python environment.
Please run pip install -r requirements.txt to make sure that the right versions of the required packages are installed or StoryToolkitAI will not run properly.
```

is telling you to run `pip install -r requirements.txt` inside your environment. 

It's also telling you that the `typing-extensions` package is not at the right version, but that will be corrected if you follow the process as I recommended.

## 5. Do not use sudo

Unless there's a very specific reason to use `sudo` before the commands, do not do it because it could mess up your environment variables, python installations, links for other apps etc. Is there a specific reason you did that?

## 6. The Resolve connection

That may have something to do with the `timecode` package you just mentioned - this is hard to tell unless you post the output of your console. But let's see what happens if you re-install everything as per instructions.

---

I hope this helps and let me know if it worked.

Have fun! :-D

**Comment by CVeyVey** [comment]
Hi Octavian,


sorry for the late reply, we had a deadline and needed to smash through editing.
I only had time now to look into your instructions in detail.
Since there was a M1 installer you released I didn’t follow through but tried that instead.
As to 5: thanks! Like I said I don’t really know what I’m doing. Will keep that in mind.

I just installed the M1 Version, works perfect for me but it crashes DaVinci when trying to render a timeline for transcription on my colleagues machine. 

On a hopefully unrelated note, we had our project completely fail on us last week, with Resolve crashing every 15 minutes and not being able to load the project (crashing at startup) and even refusing to load the last 5 automatic backups. 
We finished working in the evening on a perfectly working project and in the morning it wouldn’t load and we had to go back several versions of the automatic backups. 
The it just kept getting worse. Still no idea what’s wrong.
I am in contact with Resolve support, we are currently working with a project that was reconstructed through XMLs.
I don’t think it was related to Storytoolkit since a different project had no problems while it was running your tool


Hope you are getting some work done in your editing besides developing.
We are already using it a lot, absolutely love it!

All the best
Constantin


Cheers
Constantin

Constantin Gross
Founder | VeyVey Films
+49 177 4557185
www.veyvey-films.com <http://www.veyvey-films.com/>

VeyVey Films GmbH
Oskar-Jäger-Straße 117-123
50825 Köln









This e-mail and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. If you are not the intended recipient of this e-mail, you must neither take any action based upon its contents, nor copy or show it to anyone. Please contact the sender if you believe you have received this e-mail in error.
