### ISSUE TITLE
Does StoryToolkitAI support Transcribing using GPU (specifically AMD GPU)?

### ISSUE THREAD

**Issue by luckyluke113** [octimot/StoryToolkitAI#50]
I'm using a PC with AMD GPU, and I see that there is no option for Transcribing using my GPU.
Does StoryToolkitAI support Transcribe using GPU (specifically AMD GPU)?

![image](https://user-images.githubusercontent.com/40772328/214533787-4131a837-5f58-4933-9fcc-15a019eb4887.png)

Thanks

**Comment by octimot** [comment]
Hey there!

Storytoolkit only works on NVIDIA GPUs because of the modules we're using to enable its features. In fact, most of the mainstream AI research that is happening at the moment is either on CUDA or CPUs (CPU processing being very slow though in comparison). 

If you're planning to integrate more AI in your workflow I strongly suggest to invest in a CUDA enabled graphics card.

Cheers!

**Comment by Milor123** [comment]
> Hey there!
> 
> Storytoolkit only works on NVIDIA GPUs because of the modules we're using to enable its features. In fact, most of the mainstream AI research that is happening at the moment is either on CUDA or CPUs (CPU processing being very slow though in comparison).
> 
> If you're planning to integrate more AI in your workflow I strongly suggest to invest in a CUDA enabled graphics card.
> 
> Cheers!

And DirectML? Or RoCM in linux?
