### ISSUE TITLE
pysoundfile failed

### ISSUE THREAD

**Issue by x8086** [octimot/StoryToolkitAI#52]
librosa\util\decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.

Getting that warning message every time. How to fix?

**Comment by octimot** [comment]
This is just a warning and not really affecting the performance of the tool because it ends up using another module to do the processing.

It's probably happening because Resolve's "Audio Only" render preset is actually rendering a Quicktime MOV file instead of a a wav file. So, the tool is re-converting that to Linear PCM, and only after that, the file is being passed to AI. Unfortunately, I couldn't find a way to select Wave, Linear PCM using the API, but you could create your own render preset and then the tool will use a basic WAV file and most likely the warning will be gone. 

See this: https://github.com/octimot/StoryToolkitAI#resolve-transcription_wav-preset
