### ISSUE TITLE
Translation when transcript multiple language 

### ISSUE THREAD

**Issue by Momomio** [octimot/StoryToolkitAI#61]
Hello,

First, very great software, we start to integrate it to our workflow and so far our team is very happy with it.

We have a documentary with french commentary and spanish interview and when we transcribe with french language set as the source language we have as a result the spanish speaking part translate to french and vice versa when we transcribe with the spanish language set as the source.

It was a nice surprise, but is it possible to have in one go a transcription for a video with multiple language without translation ? (but don't kill the translation because it's still very nice to have ^^)

**Comment by Momomio** [comment]
I'm using the large model

**Comment by barzoock** [comment]
@octimot hey, anything new about that case? 
@Momomio Have you found any other tool that splits into shorter subtitles? 
thank you

**Comment by octimot** [comment]
Closing this since it's technically not possible to translate to other languages, but:
- as I mentioned, we're planning to have some sort of translation implemented soon, most likely via Assistant first because ChatGPT is really good at that too...
- we're looking how to implement the on-the-fly language detection feature you mentioned on #93
