### ISSUE TITLE
Resolve Workflow Integration

### ISSUE THREAD

**Issue by pantau000** [octimot/StoryToolkitAI#68]
It would be nice to integrate the tool to Resolve as "Workflow Integration", so that it would be started from inside Resolve (without the need to open a cmd prompt) once installed.

**Comment by octimot** [comment]
This is tricky given that the tool is meant to work also without Resolve and some python libraries might collide if the tool is started from Resolve, but we'll look into it!

**Comment by octimot** [comment]
Thanks again for the feedback, but we've been looking into it and it would take a lot of development resources to make this happen and since the Resolve API and Blackmagic support isn't reliable enough, we are not planning to make this anytime soon.

Don't get me wrong, I'm grateful that the API exists and we'll be adding more stability improvements related with the Resolve API, but at this point we're really hacking our way into making things work due to how the API was made...

Cheers!
