### ISSUE TITLE
How to use api key or large model?

### ISSUE THREAD

**Issue by renzhezhu1234** [octimot/StoryToolkitAI#95]
When i change language or model, the api key seem always be 0, and I cant save it. Should i pay for openai api token to change model?

**Comment by octimot** [comment]
Hey there!

> When i change language or model, the api key seem always be 0, and I cant save it. Should i pay for openai api token to change model?

It sounds like you're trying to change the model from the Preferences window, but you don't need to do that unless you want to set it as your new default. 

Normally, you can select the large model by selecting it in the [transcription settings window(https://github.com/octimot/StoryToolkitAI/blob/main/FEATURES.md#transcription-settings), which appears after you hit the Transcribe or Translate buttons.

The API Key set to '0' is a bug which will be fixed in the next update, see issue #87.

You can avoid the validation error, by using a valid API key which you receive if you become a [Patron](https://www.patreon.com/StoryToolkitAI) if you want to support development, or by simply setting the API Key to nothing, since the tool is free to use. 

Cheers!

**Comment by renzhezhu1234** [comment]
Thank you reply. Can you show me some markers skill to edit faster? I really don't know how to use markers to make me cut video faster. I just tried chinese transcribe and translate(It's seem like good in large model), When I mark two markers, I use render to clips, It's not render anything, I should pushed keyboard ”I“ and ”O“ the timeline, and render video by myself, It's the right way to use?

**Comment by octimot** [comment]
You can select the transcribed segments using shortcuts (`V`, or `Shift+A` etc.) and then turn them into markers in Resolve using key `M` or `Shift+M`, and carry on editing from there in Resolve - or render markers to clips etc.

We will publish more tips soon via [Patreon](https://www.patreon.com/StoryToolkitAI), as soon as we finish some updates on the tool! This is one of the advantages of supporting development.

Cheers!
