### ISSUE TITLE
Emojis in transcriptions / subtitles

### ISSUE THREAD

**Issue by boodybon** [octimot/StoryToolkitAI#99]
Hey Devs, 
This is an awesome tool 
I have 2 feature request 
1. Is there an option to turn the subtitles into a Text+  adjustment on the edit page as social media clients like to have their subtitles animated 
2. Would it be possible for the tool to add emojis to the subtitles

**Comment by octimot** [comment]
Hey there!

> Is there an option to turn the subtitles into a Text+ adjustment on the edit page as social media clients like to have their subtitles animated

We have a backlog of features that we want to add first, but this is an interesting idea we'll add in the future, if possible... Let's continue the conversation on this topic here, please: #14 

> Would it be possible for the tool to add emojis to the subtitles

I feel that this is a whole different rabbit hole since I'm not sure this is supported via SRT, VTT or other known subtitle files and by which software... Are you familiar with how would this work? Also, how would you expect these emojis to be "heard" by AI?

I've changed the title of this issue, in case you want to continue the thread - again, for no. 1, please use #14.

Cheers!

**Comment by octimot** [comment]
It seems that emojis are possible in Resolve using the Fonts that support them, but this is I feel a borderline use case for most of the tool users... Implementing this in such a way that AI returns emojis correctly would be a lot of work, which we'd prefer to invest in something else...

However, as mentioned in #14 , since version 0.18.3 you can export directly into Fusion Text nodes, so if you really want to get wild, I'd suggest you do it directly in Fusion, after you import the transcript lines from the tool!

Cheers!

**Comment by Momomio** [comment]
Hi, just want to add that sometime whisper can make emojis (using the large V2 model), but it's more nonsense than anything else...

<img width="745" alt="Capture d’écran 2023-05-09 à 10 13 48" src="https://user-images.githubusercontent.com/15261647/237046510-16c166c4-e818-4623-b535-26c45b055075.png">
